openapi: 3.0.0

info:
  title: 1st OAS app
  description: Sample app using OAS
  version: 1.0.0

paths:
  /todo:
    get:
      description: Get a todo list
      operationId: getTodoList
      parameters:
        - name: listId
          in: query
          description: ID of the list
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Get list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      description: Create a todo list
      operationId: createTodoList
      requestBody:
        description: Adding a list
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Todo"
      responses:
        "201":
          description: Todo list created successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Todo"
        default:
          description: Unexpected Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      description: Delete a todo list
      operationId: deleteTodoList
      parameters:
        - name: listId
          in: query
          description: ID of the list
          required: true
          schema:
            type: string
      responses:
        "204":
          description: No content response for successfull delete
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int32
        task:
          type: string
        created_at:
          type: string
          format: date-time
    Error:
      type: object
      properties:
        code:
          type: integer
          format: int16
        message:
          type: string
