// Package main provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.13.0 DO NOT EDIT.
package main

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Code    *int16  `json:"code,omitempty"`
	Message *string `json:"message,omitempty"`
}

// Todo defines model for Todo.
type Todo struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	Id        *int32     `json:"id,omitempty"`
	Task      *string    `json:"task,omitempty"`
}

// DeleteTodoListParams defines parameters for DeleteTodoList.
type DeleteTodoListParams struct {
	// ListId ID of the list
	ListId string `form:"listId" json:"listId"`
}

// GetTodoListParams defines parameters for GetTodoList.
type GetTodoListParams struct {
	// ListId ID of the list
	ListId string `form:"listId" json:"listId"`
}

// CreateTodoListJSONRequestBody defines body for CreateTodoList for application/json ContentType.
type CreateTodoListJSONRequestBody = Todo
